pub mod agent;
pub mod chunking;
pub mod cli;
pub mod config;
pub mod context;
pub(crate) mod context_graph;
pub mod context_input;
pub mod daemon;
pub mod doctor;
pub mod embedding;
pub mod hardware;
pub mod indexer;
pub mod ipc;
pub mod jobs;
pub(crate) mod launcher;
pub mod mcp;
pub mod merkle;
pub(crate) mod neural_metadata;
pub mod path_glob;
pub mod protocol;
pub(crate) mod query_aliases;
pub mod regex_search;
pub(crate) mod reranker;
pub mod search;
pub(crate) mod search_routing;
pub(crate) mod search_service;
pub mod symbols;
pub(crate) mod system_resources;
pub mod text;
pub mod tui;
pub mod vector_store;
pub mod walker;
pub(crate) mod web;
pub mod workspace;

/// Legacy constant kept for tests. Prefer [`embedding::model_dimensions`].
pub const EMBEDDING_DIMENSIONS: usize = 256;
